### ISSUE TITLE
Can't run the program on Windows 10

### ISSUE THREAD

**Issue by theprofi** [mindfulness-at-the-computer/mindfulness-at-the-computer.github.io#8]
Hi,
I downloaded WINDOWS ALPHA 4  from here:
https://mindfulness-at-the-computer.github.io/downloads/
Then I unzipped the archive and when I double click **mindfulness-at-the-computer.exe**
I get the following error:
![1](https://user-images.githubusercontent.com/8938883/38339175-92438dbe-3875-11e8-919e-be326aea4c58.png)

**Comment by SunyataZero** [comment]
Moved this issue here: https://github.com/mindfulness-at-the-computer/mindfulness-at-the-computer/issues/260
